#!/usr/bin/env bash

_dnsP=$(zenity --title="DNS_Config" --text "Enter Primary DNS" --entry)
_dnsS=$(zenity --title="DNS_Config" --text "Enter Secondary DNS" --entry)
zenity --info --title="DNS_Config" --text="Primary DNS $_dnsP \nSecondary DNS $_dnsS" --width="200" --height="100"

echo -e "# Generated by NetworkManager\nnameserver $_dnsP\nnameserver $_dnsS" > /etc/resolv.conf

clear
cat /etc/resolv.conf